# -*- coding: utf-8 -*-
"""Curso_SENATI_media.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10lcGQ4YPhb2ZVyN3IbhrOrTTcGZbuSuV
"""

from google.colab import drive
# Montar Google Drive
drive.mount('/content/drive')

import cv2
from matplotlib import pyplot as plt

imgOriginal =  cv2.imread("/content/drive/MyDrive/UTEC/SENATI Perú 2024/Curso SENATI/Lena.jpeg")

imgTratada = cv2.blur(imgOriginal, (5,5))

titles = ['Imagem Original','Filtro de Média']
images = [imgOriginal, imgTratada]

for i in range(2):
  plt.subplot(1,2,i+1) #escolhe posição no subplot
  plt.imshow(cv2.cvtColor(images[i], cv2.COLOR_BGR2RGB)) #utiliza imshow imagem convertendo de BGR para RGB
  plt.title(titles[i]) #coloca título
  # retira a representação dos eixos x e y
  plt.xticks([])
  plt.yticks([])

#mostra na tela
plt.show()